apiVersion: cloudcredential.openshift.io/v1
kind: CredentialsRequest
metadata:
  name: aap-aws-credentials
  namespace: openshift-cloud-credential-operator
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  secretRef:
    name: aap-aws-credentials
    namespace: {{ .Values.namespace }}
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1
    kind: AWSProviderSpec
    statementEntries:
    - effect: Allow
      action:
      - secretsmanager:GetSecretValue
      - secretsmanager:PutSecretValue
      - secretsmanager:CreateSecret
      - secretsmanager:UpdateSecret
      - secretsmanager:ListSecrets
      - secretsmanager:DescribeSecret
      resource: "*"
    - effect: Allow
      action:
      - kms:Decrypt
      - kms:Encrypt
      resource: "*"
