apiVersion: cloudcredential.openshift.io/v1
kind: CredentialsRequest
metadata:
  name: external-secrets-aws-credentials
  namespace: openshift-cloud-credential-operator
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  secretRef:
    name: external-secrets-aws-credentials
    namespace: external-secrets
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1
    kind: AWSProviderSpec
    statementEntries:
    - effect: Allow
      action:
      - secretsmanager:GetSecretValue
      - secretsmanager:ListSecrets
      resource: "*"
    - effect: Allow
      action:
      - kms:Decrypt
      resource: "*"
