apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: external-secrets
  namespace: external-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  targetNamespaces:
    - external-secrets
