apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: nested-container-runasany
  annotations:
    kubernetes.io/description: "Custom SCC for Dev Spaces container-run with user namespaces and RunAsAny UID."
allowPrivilegeEscalation: true
allowPrivilegedContainer: false
allowedCapabilities:
- SETUID
- SETGID
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: MustRunAs
  seLinuxOptions:
    type: container_engine_t
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
seccompProfiles:
- '*'
volumes:
- configMap
- csi
- downwardAPI
- emptyDir
- ephemeral
- image
- persistentVolumeClaim
- projected
- secret
