---
schemaVersion: 2.2.0
metadata:
  name: product-demos
components:
  - name: product-demos-ee
    container:
      image: 603512373452.dkr.ecr.us-east-1.amazonaws.com/udi-ansible:latest
      memoryRequest: 256M
      memoryLimit: 5Gi
      cpuRequest: 250m
      cpuLimit: 2000m
      args: ['tail', '-f', '/dev/null']
