collections:
  - name: community.general
  - name: containers.podman
  - name: ansible.windows
  - name: community.windows
  - name: infra.aap_utilities
  - name: infra.aap_configuration
  - name: infra.aap_configuration_extended
  - name: infra.ah_configuration
  - name: microsoft.ad
  - name: amazon.aws
  - name: onepassword.connect
  - name: ansible.controller
  - name: ansible.eda
  - name: infra.controller_configuration
  - name: kubernetes.core
  - name: infra.eda_configuration
  - name: infra.ee_utilities
  - name: ansible.hub
  - name: servicenow.itsm
  - name: redhat.openshift
  - name: redhat.openshift_virtualization
  - name: ansible.platform
  - name: ansible.posix
  - name: redhat.rhel_system_roles
  - name: redhat.satellite
  - name: cloud.terraform
  - name: cloud.terraform_ops
  - name: ansible.utils
