apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.username }}-devspaces-data
  namespace: {{ .Values.username }}-devspaces
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
