apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: user-admin
  namespace: {{ .Values.username }}-devspaces
  annotations:
    argocd.argoproj.io/sync-wave: "1"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: User
  apiGroup: rbac.authorization.k8s.io
  name: {{ .Values.username }}
