apiVersion: console.openshift.io/v1
kind: ConsoleLink
metadata:
  name: keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  location: ApplicationMenu
  text: Keycloak
  href: https://keycloak.{{ .Values.domain }}
  applicationMenu:
    section: Red Hat Applications
    imageURL: https://keycloak.{{ .Values.domain }}/favicon.ico
