{{- $existing := lookup "v1" "Secret" .Values.namespace "keycloak-gitlab-client-secret" }}
{{- $clientSecret := "" }}
{{- if and $existing $existing.data (index $existing.data "client-secret") }}
{{- $clientSecret = index $existing.data "client-secret" | b64dec }}
{{- else }}
{{- $clientSecret = randAlphaNum 32 }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-gitlab-client-secret
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
type: Opaque
stringData:
  client-secret: {{ $clientSecret }}
