apiVersion: k8s.keycloak.org/v2alpha1
kind: KeycloakRealmImport
metadata:
  name: gitlab-realm
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  keycloakCRName: keycloak
  placeholders:
    GITLAB_CLIENT_SECRET:
      secret:
        name: keycloak-gitlab-client-secret
        key: client-secret
  realm:
    realm: gitlab
    enabled: true
    clients:
    - clientId: gitlab
      enabled: true
      protocol: openid-connect
      publicClient: false
      standardFlowEnabled: true
      directAccessGrantsEnabled: false
      secret: $(GITLAB_CLIENT_SECRET)
      redirectUris:
      - https://{{ .Values.gitlabDomain }}/users/auth/openid_connect/callback
      webOrigins:
      - https://{{ .Values.gitlabDomain }}
      defaultClientScopes:
      - openid
      - profile
      - email
      attributes:
        pkce.code.challenge.method: S256
