apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: repo-https-secret
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: repo-https-secret
    template:
      engineVersion: v2
      data:
        username: git
        password: "{{`{{ .token }}`}}"
  data:
  - secretKey: token
    remoteRef:
      key: github
      property: token
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ansible-config
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: ansible-config
    template:
      engineVersion: v2
      data:
        ansible.cfg: |
          [galaxy]
          server_list = certified, validated, galaxy

          [galaxy_server.certified]
          url=https://console.redhat.com/api/automation-hub/content/published/
          auth_url=https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token
          token={{`{{ .automationhub_token }}`}}

          [galaxy_server.validated]
          url=https://console.redhat.com/api/automation-hub/content/validated/
          auth_url=https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token
          token={{`{{ .automationhub_token }}`}}

          [galaxy_server.galaxy]
          url=https://galaxy.ansible.com/
  data:
  - secretKey: automationhub_token
    remoteRef:
      key: ansible
      property: automationhub_token
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: quay-registry-secret
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: quay-registry-secret
    template:
      type: kubernetes.io/dockerconfigjson
      engineVersion: v2
      data:
        .dockerconfigjson: |
          {"auths":{"quay.io":{"username":"{{`{{ .username }}`}}","password":"{{`{{ .password }}`}}","auth":"{{`{{ printf "%s:%s" .username .password | b64enc }}`}}"}}}
  data:
  - secretKey: username
    remoteRef:
      key: quay
      property: username
  - secretKey: password
    remoteRef:
      key: quay
      property: password
