apiVersion: v1
kind: Secret
metadata:
  name: htpasswd-secret
  namespace: openshift-config
  annotations:
    argocd.argoproj.io/sync-wave: "0"
type: Opaque
stringData:
  htpasswd: |
    user1:$2y$05$byow7BTf17TbS0C1FFcnAecuQ1ywse3exyGiX/UxzUES6GgyPqKDe
    user2:$2y$05$08IQBgVkngR98ZLC4rJfke11qwHm4oGfva68/4.wxsERwxkrrILbG
    user3:$2y$05$iQ/gxE/RXEa4eGeMsIOrxeQZnquuOrpL1QOswI2RwFkrJ/HTmft2m
    user4:$2y$05$psieg7owdgfCgozuxziid.QTaQgB1DzgImcIUiDzoPJbMTjR8Rqdm
    user5:$2y$05$/2a5NdPpGrSlREQPTmDAE.4BmdJJDLLSPTzZc3YXRmy6wh1sVDNxa
