{{- range .Values.users }}
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ . }}
  namespace: openshift-gitops
spec:
  description: "Self-service project for {{ . }}"
  sourceRepos:
    - '*'
  destinations:
    - namespace: '{{ . }}-*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
{{- end }}
