apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: vault
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  targetNamespaces:
    - {{ .Values.namespace }}
