---
- name: Populate AWS Secrets Manager for External Secrets
  hosts: localhost
  gather_facts: false

  vars:
    secrets:
      - name: github
        description: GitHub personal access token for repo-https-secret
        value: "{{ {'token': github_token} | to_json }}"
      - name: ansible
        description: Automation Hub token for ansible-config secret
        value: "{{ {'automationhub_token': automationhub_token} | to_json }}"
      - name: quay
        description: Quay.io registry credentials
        value: "{{ {'username': quay_username, 'password': quay_password} | to_json }}"

  tasks:
    - name: Create or update secrets in AWS Secrets Manager
      ansible.builtin.shell:
        cmd: >-
          aws secretsmanager put-secret-value
          --secret-id '{{ item.name }}'
          --secret-string '{{ item.value }}'
          2>/dev/null
          ||
          aws secretsmanager create-secret
          --name '{{ item.name }}'
          --description '{{ item.description }}'
          --secret-string '{{ item.value }}'
      loop: "{{ secrets }}"
      loop_control:
        label: "{{ item.name }}"
      no_log: false

    - name: Secrets Manager population complete
      ansible.builtin.debug:
        msg: >-
          All 3 secrets created/updated in AWS Secrets Manager:
          github, ansible, quay
...
