---
- name: Populate AWS Secrets Manager for External Secrets
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Create github secret
      amazon.aws.secretsmanager_secret:
        name: github
        description: GitHub personal access token for repo-https-secret
        secret: "{{ {'token': github_token} | to_json }}"

    - name: Create ansible secret
      amazon.aws.secretsmanager_secret:
        name: ansible
        description: Automation Hub token for ansible-config secret
        secret: "{{ {'automationhub_token': automationhub_token} | to_json }}"

    - name: Create rhsm secret
      amazon.aws.secretsmanager_secret:
        name: rhsm
        description: Red Hat Subscription Manager credentials
        secret: "{{ {'username': rhsm_username, 'password': rhsm_password} | to_json }}"

    - name: Create quay secret
      amazon.aws.secretsmanager_secret:
        name: quay
        description: Quay.io registry credentials
        secret: "{{ {'username': quay_username, 'password': quay_password} | to_json }}"

    - name: Secrets Manager population complete
      ansible.builtin.debug:
        msg: >-
          All 4 secrets created/updated in AWS Secrets Manager:
          github, ansible, rhsm, quay
...
