{{- $kcSecret := lookup "v1" "Secret" "keycloak" "keycloak-gitlab-client-secret" }}
{{- $clientSecret := "WAITING_FOR_KEYCLOAK_SECRET" }}
{{- if and $kcSecret $kcSecret.data (index $kcSecret.data "client-secret") }}
{{- $clientSecret = index $kcSecret.data "client-secret" | b64dec }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-keycloak-oidc
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
type: Opaque
stringData:
  provider: |
    name: openid_connect
    label: Keycloak
    args:
      name: openid_connect
      scope:
        - openid
        - profile
        - email
      response_type: code
      issuer: https://keycloak.{{ .Values.domain }}/realms/gitlab
      discovery: true
      pkce: true
      client_auth_method: basic
      client_options:
        identifier: gitlab
        secret: {{ $clientSecret }}
        redirect_uri: https://gitlab.{{ .Values.domain }}/users/auth/openid_connect/callback
