apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitlab-keycloak-oidc
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: gitlab-keycloak-oidc
    template:
      engineVersion: v2
      data:
        provider: |
          name: openid_connect
          label: Keycloak
          args:
            name: openid_connect
            scope:
              - openid
              - profile
              - email
            response_type: code
            issuer: https://keycloak.{{ .Values.domain }}/realms/gitlab
            discovery: true
            pkce: true
            client_auth_method: basic
            client_options:
              identifier: gitlab
              secret: {{`{{ .client_secret }}`}}
              redirect_uri: https://gitlab.{{ .Values.domain }}/users/auth/openid_connect/callback
  data:
  - secretKey: client_secret
    remoteRef:
      key: keycloak
      property: gitlab-client-secret
