apiVersion: apps.gitlab.com/v1beta1
kind: GitLab
metadata:
  name: gitlab
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  chart:
    values:
      global:
        hosts:
          domain: {{ .Values.domain }}
        ingress:
          provider: none
          configureCertmanager: false
      nginx-ingress:
        enabled: false
      certmanager:
        install: false
