{{- $ingress := lookup "config.openshift.io/v1" "Ingress" "" "cluster" }}
{{- $domain := "apps.example.com" }}
{{- if and $ingress $ingress.spec }}
{{- $domain = $ingress.spec.domain }}
{{- end }}
apiVersion: apps.gitlab.com/v1beta1
kind: GitLab
metadata:
  name: gitlab
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  chart:
    version: {{ .Values.chartVersion | quote }}
    values:
      global:
        hosts:
          domain: {{ $domain }}
        ingress:
          provider: none
          configureCertmanager: false
      nginx-ingress:
        enabled: false
      certmanager:
        install: false
