apiVersion: apps.gitlab.com/v1beta1
kind: GitLab
metadata:
  name: gitlab
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  chart:
    version: {{ .Values.chartVersion | quote }}
    values:
      global:
        hosts:
          domain: {{ .Values.domain }}
        ingress:
          provider: none
          configureCertmanager: false
      nginx-ingress:
        enabled: false
      certmanager:
        install: false
      gitlab:
        gitlab-shell:
          minReplicas: 1
          maxReplicas: 1
        webservice:
          minReplicas: 1
          maxReplicas: 1
          resources:
            requests:
              cpu: 200m
              memory: 1500M
        sidekiq:
          minReplicas: 1
          maxReplicas: 1
          resources:
            requests:
              cpu: 200m
              memory: 1G
        gitlab-exporter:
          resources:
            requests:
              cpu: 50m
              memory: 64M
        kas:
          minReplicas: 1
          maxReplicas: 1
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
      registry:
        minReplicas: 1
        maxReplicas: 1
        resources:
          requests:
            cpu: 25m
            memory: 32Mi
